Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/10/2024
Var
contador : inteiro


Inicio
enquanto (contador <100) faca
escreval(contador)
contador <- contador + 1
se (contador %10 = 0) entao
escreval(contador, "- Numero multiplo de dez")
fimse
fimenquanto


Fimalgoritmo