Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/10/2024
Var
// Seção de Declarações das variáveis 
nome, email: caractere
idade : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreva("Boa tarde digite o seu nome")
 leia(nome)
 

Fimalgoritmo