Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/10/2024
Var
num1, soma, i: inteiro


Inicio
enquanto (i < 4) faca
escreval("Digite um numero")
leia(num1)
soma <- num1 + soma
i <- i +1

fimenquanto
escreval("A soma dos 4 numero é igual: ", soma)


Fimalgoritmo