Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/10/2024
Var
contador, resultado : inteiro


Inicio
enquanto (contador <=10) faca
resultado <- 8 * contador
escreval("8 x",contador, " =", resultado)
contador <- contador +1
resultado <- 8 * contador
fimenquanto



Fimalgoritmo